name: iris-mlops-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow==2.13.0
      - azureml-mlflow==1.56.0
      - scikit-learn==1.4.2
      - pandas==2.2.2
      - numpy==1.26.4
